name: millionaire_game
description: Who Wants to Be a Millionaire? game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.8.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.7
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.2
  persistent_bottom_nav_bar_v2: ^6.0.1
  go_router: ^15.1.2
  image_picker: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  path_provider: ^2.1.5
  intl: ^0.19.0
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^11.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/


  
  